POST http://localhost:8080/user/register
Content-Type: application/json

{
  "public_key": "MIIBCgKCAQEAzxnXj3tWQw3eB6h5wpVx8sf2h7EJBl+LR8lliWBotzhtUF14b6p8NSsrPx6ymTr2Z+m+m43X8TlDeDPA2f1/Zy5eh9Ewdo2eXLv/NLPcg8DChMPNSPHOl4XpAv2WIcowirwb6PdTganqkPtgO1zqn+xFdMwHwFWDSZJxXU9FhNYyvP2mxHp8dNnqgcFXeFIUmxEmJYJHoEKopksVN3ifnFYfLdo05gKEHqkXIvGeo/bleaH7ZLbG714gjBozlK1plnGCuj63oVoMsMf1pgzujo1oOBgBQrRKWcSuWNG5OnbfH76VB2t8Qd8DPupswYiVA1M/D/Eut4FGhQDvEBIBTQIDAQAB"
}


###

POST  http://localhost:8080/status/create
Content-Type: application/json
user_id: 3

{
  "text": "kdcdk c c dcdk cdwcd ckwd kd ckd kd"
}

###

DELETE http://localhost:8080/status/3
user_id: 1

###

POST http://localhost:8080/status/reply
Content-Type: application/json
user_id: 1

{
  "reply": "kdcdk c c dcdk cdwcd ckwd kd ckd kd",
  "status_id": 13
}

###
POST http://localhost:8080/conversation
Content-Type: application/json
user_id: 1

{
  "message_id": 10,
  "conversation_id": 3
}
